### ISSUE TITLE
code for visualization

### ISSUE THREAD

**Issue by zhou00NJUST** [jackyzengl/DADA#3]
Hi! Thank you for your fantastic work! I’m studying your code and would appreciate guidance on how to generate trajectories with its corresponding video frames, as shown in the right of Figure 1 in your paper. Any related code or advice would be really helpful.

Best regards,

**Comment by haofuly** [comment]
@xzhouNJUST Sorry for late response. Firstly, you should modify the [dataset script](https://github.com/jackyzengl/DADA/blob/main/models/sgan/sgan/data/trajectories.py) to load [frame_id](https://github.com/jackyzengl/DADA/blob/main/datasets/A2B/train_origin/biwi_eth_train.txt). Secondly, as the frame Interval is 0.4s, the frame_id could be associated with video. Finally, the original ETH and UCY dataset has provided the homography matrix  to project the pixel trajectory to world coordinate.

**Comment by haofuly** [comment]
Detailed at #4
